server:
    port: 8010

spring:
    application:
        name: microservice-consumer-movie
    jta:
        atomikos:
            properties:
                transaction-manager-unique-name:
eureka:
    client:
        service-url:
            defaultZone: http://discovery:8761/eureka/
    instance:
        prefer-ip-address: true

management:
    security:
        enabled: false