server:
    port: 8080


spring:
    application:
        name: microservice-config-server

    cloud:
        config:
            server:
                git:
                    skipSslValidation: true
                    uri: https://github.com/JasonkayZK/Spring_Cloud_Learn/ # 配置Git仓库的地址
                    username:  # Git仓库账号
                    password:  # Git仓库密码
                health:
                    repositories:
                        a-foo:
                            label: basic-config-v2
#                            label: fault
                            name: microservice-foo
                            profiles: dev



