server:
    port: 8010
spring:
    application:
        name: microservice-consumer-movie
    zipkin:
        base-url: http://localhost:9411
    sleuth:
        sampler:
            percentage: 1.0
logging:
    level:
        org.springframework.cloud.sleuth: DEBUG
