server:
    port: 8071

spring:
    application:
        name: microservice-comsumer-movie

eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka/
    instance:
        prefer-ip-address: true

management:
    security:
        enabled: false

