server:
    port: 8080

spring:
    application:
        name: microservice-config-server
    cloud:
        config:
            server:
                git:
                    skipSslValidation: true
                    uri: https://github.com/JasonkayZK/Spring_Cloud_Learn/ # 配置Git仓库的地址
                    username:  # Git仓库账号
                    password:  # Git仓库密码
security:
    basic:
        enabled: true # 开启基于HTTP basic的认证
    user:
        name: user # 配置登录的账号是user
        password: password123 # 配置登录的密码是password123

management:
    security:
        enabled: false