server:
    port: 8080


spring:
    application:
        name: microservice-config-server-eureka
    cloud:
        config:
            server:
                git:
                    skipSslValidation: true
                    uri: https://github.com/JasonkayZK/Spring_Cloud_Learn/ # 配置Git仓库的地址
                    username:  # Git仓库账号
                    password:  # Git仓库密码
eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka/

management:
    security:
        enabled: false
