server:
    port: 8761   # 指定该Eureka实例的端口

security:
    basic:
        enabled: true # 开启基于HTTP basic的认证
    user:
        name: zk # 配置登录的账号
        password: zk137818 # 配置登录的密码

eureka:
    client:
        registerWithEureka: false
        fetchRegistry: false
        serviceUrl:
            defaultZone: http://zk:zk137818@localhost:8761/eureka/

# 参考文档：http://projects.spring.io/spring-cloud/docs/1.0.3/spring-cloud.html#_standalone_mode
# 参考文档：http://my.oschina.net/buwei/blog/618756