server:
    port: 8080


spring:
    application:
        name: microservice-config-server

    cloud:
        config:
            server:
                git:
                    skipSslValidation: true
                    uri: https://github.com/JasonkayZK/Spring_Cloud_Learn/ # 配置Git仓库的地址
                    username:  # Git仓库账号
                    password:  # Git仓库密码
        bus:
            trace:
                enabled: true # 开启cloud bus的跟踪

    rabbitmq:
        host: localhost
        port: 5672
        username: guest
        password: guest


management:
    security:
        enabled: false